"""
born_substrate_sampling.py
==========================

Does the Born |psi|^2 weighting fall OUT of a random-phase substrate bath, or does
it have to be put in?  (The "run" of 2026-07-01, cf. drafts/NOTE_wave_energy_interpretation.md.)

Model (substrate realism -> detector statistics)
------------------------------------------------
A detector atom is a THRESHOLD ESCAPE CLOCK (Kramers/Arrhenius): a metastable
"unfired" grain that escapes over a barrier at rate r0*exp(eps/D).  It is driven by a
weak REAL oscillation of the vacuum substrate -- amplitude a*|psi_i|, phase arg(psi_i)
-- and it sits in the disordered bulk, which supplies a bath of noise intensity D and,
crucially, a UNIFORMLY RANDOM phase (the "mostly disorganised, tiny-coherent" bulk).

Instantaneous rate:   r_i(t) = r0 * exp( eps_i(t)/D ),
                       eps_i(t) = a|psi_i| cos(w t + phi_i + xi),   xi ~ bulk phase.

Phase-average over the random bulk phase:
       <r_i> = r0 * I0( a|psi_i|/D )  ~  r0 * (1 + (1/4)(a|psi_i|/D)^2 + ...)
The LINEAR term <cos> = 0 cancels (signed amplitude cancels); the first survivor is
the POWER.  So the phase-averaged EXCESS rate

       Delta r_i  =  r0 [ I0(A_i) - 1 ]  ~  (r0/4)(a/D)^2 |psi_i|^2   (weak drive A_i<<1)

is proportional to |psi_i|^2 -- the squaring is GENERATED by the bath average, not
imported from a golden rule.  An indivisible electron fires exactly one atom
(winner-take-all among competing Poisson processes):

       P(i) = Delta r_i / sum_j Delta r_j  ->  |psi_i|^2 / sum|psi_j|^2   (= Born, weak limit).

What is DERIVED here: the |psi|^2 weighting from delivered power + phase cancellation.
What stays ASSUMED: (A) psi is a real energy-carrying oscillation (drive linear in psi);
(B) the bulk phase is uniformly random & independent per trial -- the substrate
"quantum equilibrium" / typicality condition.  Break either and Born should FAIL:
this script checks that it does.

Four experiments
----------------
 (1) Rate law:      <exp(A cos t)>_t - 1   vs   I0(A)-1   vs   A^2/4    (excess ~ |psi|^2 when weak)
 (2) Born:          winner-take-all frequencies vs |psi_i|^2  (discrete channels + interference pattern)
 (3) Break A|psi|/D>>1 (strong signal):  super-quadratic -> bright channels over-weighted (Born deviation)
 (4) Break random phase (coherent bath):  linear term survives -> weighting depends on arg(psi) (Born violated)

numpy + matplotlib only.  Deterministic.
"""

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

rng = np.random.default_rng(20260701)

# ---------------------------------------------------------------- helpers
_THGRID = np.linspace(0.0, 2.0 * np.pi, 4000, endpoint=False)

def I0(A):
    """Modified Bessel I0(A) = <exp(A cos theta)> over uniform theta (no scipy)."""
    A = np.asarray(A, dtype=float)
    return np.exp(A[..., None] * np.cos(_THGRID)).mean(axis=-1)

def excess_rate(A):
    """Phase-averaged excess escape rate over the dark baseline, in units of r0."""
    return I0(A) - 1.0

def tvd(p, q):
    """Total variation distance between two distributions."""
    return 0.5 * np.abs(np.asarray(p) - np.asarray(q)).sum()

def winner_frequencies(weights, ntrials):
    """Winner-take-all: draw the single fired atom ~ categorical(weights), many trials."""
    p = np.asarray(weights, float)
    p = p / p.sum()
    winners = rng.choice(len(p), size=ntrials, p=p)
    return np.bincount(winners, minlength=len(p)) / ntrials

# ================================================================ EXP 1: rate law
A_axis = np.linspace(0.02, 3.0, 40)
# Monte-Carlo phase average, to show it is not an analytic artifact:
M = 400_000
xi = rng.uniform(0.0, 2.0 * np.pi, M)
dr_mc = np.array([np.mean(np.exp(a * np.cos(xi))) - 1.0 for a in A_axis])
dr_theory = excess_rate(A_axis)          # I0(A)-1
dr_quad = A_axis**2 / 4.0                 # weak-signal law  ~ |psi|^2

# ================================================================ EXP 2/3: discrete-channel Born
# Born target probabilities (|psi_i|^2) for a 4-outcome state:
p_born = np.array([0.46, 0.30, 0.16, 0.08])
p_born = p_born / p_born.sum()
amp = np.sqrt(p_born)                     # |psi_i|

NTRIALS = 400_000
a_weak = 0.15                             # a/D small -> A_i = a_weak*|psi_i| << 1  (Born regime)
a_strong = 3.0                            # a/D large -> saturation (deviation regime)

lam_weak = excess_rate(a_weak * amp)      # ~ |psi_i|^2
lam_strong = excess_rate(a_strong * amp)  # super-quadratic
p_eff_weak = lam_weak / lam_weak.sum()    # model's own prediction (no sampling noise)
p_eff_strong = lam_strong / lam_strong.sum()

freq_weak = winner_frequencies(lam_weak, NTRIALS)
freq_strong = winner_frequencies(lam_strong, NTRIALS)

tvd_weak = tvd(freq_weak, p_born)
tvd_strong = tvd(freq_strong, p_born)
tvd_model_weak = tvd(p_eff_weak, p_born)      # pure model bias, weak
tvd_model_strong = tvd(p_eff_strong, p_born)  # pure model bias, strong

# ================================================================ EXP 2b: interference pattern (the hologram tie-in)
Nx = 240
xg = np.linspace(-6.0, 6.0, Nx)
k1, k2, w = 2.2, 3.0, 3.2
psi_x = (np.exp(1j * k1 * xg) + np.exp(1j * k2 * xg)) * np.exp(-xg**2 / (2 * w**2))
p_born_x = np.abs(psi_x)**2
p_born_x = p_born_x / p_born_x.sum()
amp_x = np.abs(psi_x)
A_x = 0.12 * amp_x / amp_x.max()          # weak everywhere
lam_x = excess_rate(A_x)
freq_x = winner_frequencies(lam_x, 1_500_000)
tvd_x = tvd(freq_x, p_born_x)

# ================================================================ EXP 4: bath-coherence break (random phase is load-bearing)
# Two channels of EQUAL amplitude (Born must give 50/50) but different phase arg(psi).
# Bath phase ~ von Mises(mu=0, kappa): kappa=0 is uniform/random (equilibrium, Born);
# large kappa is a coherent bulk.  |psi|^2 is blind to arg(psi); a coherent bath is NOT.
amp2 = np.array([1.0, 1.0]) / np.sqrt(2.0)     # |psi|^2 = 0.5, 0.5
delta = np.array([0.0, np.pi / 2.0])           # distinct phases; Born is blind to these
A2 = 0.9 * amp2

M2 = 200_000
kappa_list = [0.0, 0.5, 1.0, 2.0, 4.0]         # 0 = random/Born ; larger = more coherent bulk
coh_weights = []
for kap in kappa_list:
    th = rng.vonmises(0.0, kap, M2)            # peaked-at-0 bath phase (kap=0 -> uniform)
    rate = np.array([np.mean(np.exp(A2[c] * np.cos(th + delta[c]))) - 1.0 for c in range(2)])
    coh_weights.append(rate / rate.sum())
coh_weights = np.array(coh_weights)            # rows: kappa; cols: channel
rand_ctrl = coh_weights[0]                      # kappa=0 == random-phase control (Born)

# ================================================================ REPORT
print("=" * 74)
print("BORN FROM A RANDOM-PHASE SUBSTRATE BATH  -- numerical test")
print("=" * 74)
print("\n[1] Rate law  Delta r = I0(A)-1 :  excess ~ A^2/4 (|psi|^2) at weak drive")
for a in (0.05, 0.2, 0.5, 1.0, 2.0):
    print(f"    A={a:4.2f} : I0-1={excess_rate(np.array([a]))[0]:.5f}"
          f"   A^2/4={a*a/4:.5f}   ratio={excess_rate(np.array([a]))[0]/(a*a/4):.3f}")
print("    -> ratio ~ 1 while A<<1 (squaring is the delivered POWER); grows for A>~1 (saturation).")

print(f"\n[2] Born, discrete 4-channel state |psi_i|^2 = {np.round(p_born,3)}")
print(f"    WEAK bath (a/D={a_weak}):   winner freqs = {np.round(freq_weak,3)}")
print(f"                                 model p_eff  = {np.round(p_eff_weak,3)}")
print(f"    TVD(freq, Born)      = {tvd_weak:.4f}   (model bias alone {tvd_model_weak:.4f}; rest is MC noise)")

print(f"\n[2b] Born, interference pattern (240 sites):  TVD(hist, |psi(x)|^2) = {tvd_x:.4f}")
print( "     -> winner histogram reproduces the |psi(x)|^2 fringes.")

print(f"\n[3] BREAK 1 -- strong signal (a/D={a_strong}):")
print(f"    winner freqs = {np.round(freq_strong,3)}   vs Born {np.round(p_born,3)}")
print(f"    TVD(freq, Born) = {tvd_strong:.4f}  (model bias {tvd_model_strong:.4f}) "
      f"-> {tvd_strong/max(tvd_weak,1e-9):.0f}x the weak-bath TVD: bright channels over-weighted.")

print(f"\n[4] BREAK 2 -- bath coherence (von Mises kappa). Two EQUAL-|psi| channels, phases 0 and pi/2:")
print(f"    Born prediction (phase-blind)      : [0.500 0.500]")
for kap, wgt in zip(kappa_list, coh_weights):
    tag = "random / Born" if kap == 0 else "coherent bulk"
    print(f"    kappa={kap:4.1f} ({tag:13s})   : {np.round(wgt,3)}   TVD(Born)={tvd(wgt,[0.5,0.5]):.3f}")
print("    -> kappa=0 (random phase) gives 50/50; coherence skews it by arg(psi). Born fails.")
print("\n    => random, decorrelated bulk phase is LOAD-BEARING: it is the typicality /")
print("       'quantum-equilibrium' condition that turns delivered power into Born.")

# ================================================================ FIGURE
fig, ax = plt.subplots(2, 2, figsize=(13, 9))

# (0,0) rate law
a0 = ax[0, 0]
a0.plot(A_axis, dr_theory, "-", lw=2, label=r"$I_0(A)-1$  (phase-averaged excess)")
a0.plot(A_axis, dr_quad, "--", lw=2, label=r"$A^2/4 \propto |\psi|^2$  (weak-signal law)")
a0.plot(A_axis, dr_mc, ".", ms=5, alpha=0.6, label="Monte-Carlo phase avg")
a0.axvspan(0, 0.5, color="tab:green", alpha=0.08)
a0.text(0.16, a0.get_ylim()[1]*0.0 + 0.05, "weak-signal\n(Born) regime", color="tab:green", fontsize=9)
a0.set_xlabel(r"drive strength $A = a|\psi|/D$")
a0.set_ylabel(r"excess firing rate $\Delta r/r_0$")
a0.set_title("(1) The squaring is generated: linear term cancels,\npower survives  " + r"$\Rightarrow \Delta r \propto |\psi|^2$")
a0.legend(fontsize=9); a0.grid(alpha=0.3)

# (0,1) discrete Born + strong-signal break
a1 = ax[0, 1]
idx = np.arange(len(p_born)); bw = 0.27
a1.bar(idx - bw, p_born, bw, label=r"Born $|\psi_i|^2$", color="k", alpha=0.85)
a1.bar(idx, freq_weak, bw, label=f"random bath (a/D={a_weak})", color="tab:green")
a1.bar(idx + bw, freq_strong, bw, label=f"strong signal (a/D={a_strong})", color="tab:red", alpha=0.85)
a1.set_xticks(idx); a1.set_xticklabels([f"ch{ i+1}" for i in idx])
a1.set_ylabel("outcome frequency")
a1.set_title(f"(2,3) Born recovered when weak (TVD={tvd_weak:.3f});\nbroken when strong (TVD={tvd_strong:.3f})")
a1.legend(fontsize=9); a1.grid(alpha=0.3, axis="y")

# (1,0) interference pattern
a2 = ax[1, 0]
a2.plot(xg, p_born_x, "-", lw=2, color="k", label=r"$|\psi(x)|^2$ (Born target)")
a2.plot(xg, freq_x, ".", ms=4, color="tab:blue", alpha=0.7, label="winner-take-all histogram")
a2.set_xlabel("detector position $x$"); a2.set_ylabel("landing probability")
a2.set_title(f"(2b) Winner histogram reproduces the\ninterference fringes  (TVD={tvd_x:.3f})")
a2.legend(fontsize=9); a2.grid(alpha=0.3)

# (1,1) bath-coherence break: channel-1 fraction vs bath coherence kappa
a3 = ax[1, 1]
ch1 = coh_weights[:, 0]
a3.axhline(0.5, color="k", ls="--", lw=2, label="Born (phase-blind) = 0.5")
a3.plot(kappa_list, ch1, "o-", lw=2, ms=8, color="tab:purple", label="channel-1 fraction")
a3.fill_between(kappa_list, 0.5, ch1, color="tab:purple", alpha=0.12)
a3.set_xlabel(r"bath coherence $\kappa$  (0 = random / equilibrium)")
a3.set_ylabel("outcome fraction, channel 1")
a3.set_ylim(0.45, 1.02)
a3.set_title("(4) Equal-$|\\psi|$ channels: random bath ($\\kappa$=0) $\\to$ 0.5 (Born);\ncoherent bulk skews by arg($\\psi$) $\\to$ Born violated")
a3.legend(fontsize=9); a3.grid(alpha=0.3)

fig.suptitle("Born as energy-driven detection statistics in a random-phase substrate bath "
             "(DiracKuramoto / wave-energy route)", fontsize=13, y=0.995)
fig.tight_layout(rect=[0, 0, 1, 0.98])
out = "code/born_substrate_sampling.png"
fig.savefig(out, dpi=130)
print(f"\nfigure -> {out}")
